### ISSUE TITLE
@typeschema/valibot: not assignable to parameter of type "Cannot find module 'valibot'"

### ISSUE THREAD

**Issue by sexnine** [decs/typeschema#57]
- @typeschema/valibot v0.13.4
- valibot v0.31.0

The following code:
```ts
import { wrap } from "@typeschema/valibot";
import { object, string } from "valibot";

wrap(
  object({
    token: string(),
  }),
)
```

Gives the TS error:
> TS2345: Argument of type
> ```ts
> ObjectSchema<{
>      readonly token: StringSchema<undefined>; 
> }, undefined>
> ```
> is not assignable to parameter of type "Cannot find module 'valibot'"

I do have `valibot` installed.
For context, this is part of a SvelteKit app using PNPM as pkg manager.
I haven't had this issue with past versions of typeschema.

I'm thinking the issue might have something to do with PNPM, I'll try to make a short reproduction of the issue.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/decs) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/decs/typeschema/issues/57">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/decs/typeschema/issues/57/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/decs/typeschema/issues/57/pledge.svg">
</picture>
</a>

**Comment by marchellodev** [comment]
Facing the same issue after upgrading to 0.31.0

**Comment by decs** [comment]
Landed #58 and released it as `@typeschema/valibot v0.13.5` and `@typeschema/main v0.13.10`

Thanks @matt45400 and @fabian-hiller for the fix!
